### PR TITLE
Check name and metrics for encoding MetricFamilys

### PR DESCRIPTION
**Pull request by overvenus**

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

PTAL @disksing

**Comment by disksing** [comment]
LGTM.

**Comment by ndenev** [comment]
I have a problem that seems to be related to this change.
As far as I can see before there was only check if the metric family has name, but now it is also checked if there are any metrics. This is a problem in cases where you have an error counter for example that is rarely updated.
When I check for the result of `gather()` it is indicating error, also even if decide to ignore this error the Encoder stops processing metrics when it sees a metric family without metrics, and if the problematic error counter is first nothing will be encoded.

**Comment by ndenev** [comment]
As a workaround I'm updating the error `Counter` with `inc_by(0.0)` in the successful code path.

**Comment by overvenus** [comment]
Hi @ndenev! Thank you for your feedback, and sorry for my slow reply.

It looks like `gather` returns an emptied MetricFamily which is the error `Counter`. I have just sent a PR(#154) for this :grinning:

**Comment by overvenus** [comment]
FYI, rust-prometheus v0.3.13 is released.  It no longer`gather`s empty MetricFamily.

**Pull request merged**
