### PR TITLE
*: add protobuf encoder

### LINKED ISSUE #7: support output with text and protobuf  format
- [x] Text format
- [x] Protocol buffer format

https://prometheus.io/docs/instrumenting/exposition_formats/

### PR DESCRIPTION
**Pull request by overvenus**
This PR add a protobuf encoder and it becomes the default encoder for push feature.

PTAL @siddontang @BusyJay 

Close #7

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by overvenus** [comment]
proto.rs generated by protobuf 1.1.0 seems not compatible with 1.0.

**Comment by siddontang** [comment]
> proto.rs generated by protobuf 1.1.0 seems not compatible with 1.0.

What's the problem here?

**Comment by overvenus** [comment]
```
error[E0412]: type name `protobuf::CachedSize` is undefined or not in scope
  --> /home/neil/.cargo/git/checkouts/rust-prometheus-5310701f77ec76f6/c6d4bf5/src/proto.rs:30:18
   |
30 |     cached_size: ::protobuf::CachedSize,
   |                  ^^^^^^^^^^^^^^^^^^^^^^ undefined or not in scope
   |
   = help: no candidates by the name of `CachedSize` found in your project; maybe you misspelled the name or forgot to import an external crate?

error[E0425]: unresolved name `protobuf::reflect::accessor::make_singular_field_accessor`
   --> /home/neil/.cargo/git/checkouts/rust-prometheus-5310701f77ec76f6/c6d4bf5/src/proto.rs:223:29
    |
223 |                 fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unresolved name
```

Complied with protobuf 1.0.

**Comment by siddontang** [comment]
so how can do? upgrade all to protobuf 1.1.0?

**Comment by overvenus** [comment]
Yep, or stay still with `#[allow(deprecated)]`. I perfer updating protobuf to 1.1, and we should increase prometheus version later.

**Comment by siddontang** [comment]
please upgrade protobuf, and increase version.

**Comment by overvenus** [comment]
PTAL @siddontang 
metrics.rs is generated by rust-protobuf v1.2.1

**Comment by siddontang** [comment]
LGTM

@disksing

**Comment by disksing** [comment]
Rust:beta and Rust:nightly failed:
```
error: unused `#[macro_use]` import
  --> examples/example_process_collector.rs:14:1
   |
14 | #[macro_use]
   | ^^^^^^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`
```

**Comment by siddontang** [comment]
```
error: you should put `HistogramOpts` between ticks in the documentation
   --> src/macros.rs:104:14
    |
104 | /// Create a HistogramOpts
    |              ^^^^^^^^^^^^^
    |
    = note: `-D doc-markdown` implied by `-D warnings`
    = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#doc_markdown
error: you should put `CounterVec` between ticks in the documentation
   --> src/macros.rs:187:14
    |
187 | /// Create a CounterVec and register to default registry.
    |              ^^^^^^^^^^
    |
    = note: `-D doc-markdown` implied by `-D warnings`
    = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#doc_markdown
```

**Comment by siddontang** [comment]
```
---- registry::tests::test_default_registry stdout ----
	thread 'registry::tests::test_default_registry' panicked at 'assertion failed: `(left == right)` (left: `7`, right: `1`)', src/registry.rs:319
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    registry::tests::test_default_registry

```

**Comment by siddontang** [comment]
LGTM

PTAL @disksing

**Comment by disksing** [comment]
LGTM.

**Pull request merged**
