### PR TITLE
Bump to 0.3.1

### PR DESCRIPTION
**Pull request by overvenus**
+ update protobuf to v1.4.
 + update [proto/metrics.rs](https://github.com/pingcap/rust-prometheus/blob/2ee84f33900bd9ba09d17193af1cdd04083e74c5/proto/metrics.rs).
 + update README.md.
 + include benches folder for packaging, see more: https://github.com/rust-lang/cargo/issues/4365#issuecomment-320497120 .
 + fix some warnings.

CC: https://github.com/rust-lang/rust/issues/43675

### CODE REVIEW

**Comment by siddontang** [comment]
CI failed @overvenus

**Comment by siddontang** [comment]
CI still failed.

**Comment by siddontang** [comment]
any update? @overvenus

**Comment by overvenus** [comment]
The CI failure is caused by the outdated clippy. We should wait latest clippy or specify versions of rustc and clippy.

**Pull request merged**
