### PR TITLE
Use std atomic types (rustc 1.34 has stabilized)

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

### CODE REVIEW

**Comment by ngaut** [comment]
Good job.

**Comment by breeswish** [comment]
@overvenus PTAL

**Comment by siddontang** [comment]
seem now the atomic feature is stable, we don't need the benchmark which is designed to compare the Atomic Vs Mutex for Number before.

@breeswish @overvenus

**Comment by breeswish** [comment]
@siddontang Yes, we can remove it later. Not very necessary in this PR.

**Comment by vkrasnov** [comment]
Hi, I think this is a very important fix. Would be great to see it merged

**Comment by nrc** [comment]
@overvenus PTAL (blocked on your review iiuc)

**Pull request merged**
