### PR TITLE
Implement Debug on GenericCounter

### PR DESCRIPTION
**Pull request by kornelski**
I wanted to put counters in a struct that needs to have a `Debug`, so it's easiest if the counters have it too.

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @kornelski 

PTAL @breeswish @overvenus

**Comment by breeswish** [comment]
Thanks! Would you also like to implement Display for them?

**Comment by kornelski** [comment]
No, `Display` is more opinionated and I don't have a strong opinion how they should be displayed :)

**Comment by breeswish** [comment]
@kornelski That's Ok :)

**Pull request merged**
