### PR TITLE
encoder: remove no metrics error

### LINKED ISSUE #47: It is not an error for a MetricFamily to have no metrics

### PR DESCRIPTION
**Pull request by overvenus**
close #47 

PTAL @siddontang @disksing

### CODE REVIEW

**Comment by siddontang** [comment]
CI failed

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @disksing

**Comment by syepes** [comment]
+1

**Comment by disksing** [comment]
LGTM

**Pull request merged**
