### PR TITLE
[WIP] vec: enhance performance

### PR DESCRIPTION
**Pull request by overvenus**
Benchmarks:

master nightly:

```
test histogram::bench_histogram_with_label_values       ... bench:         131 ns/iter (+/- 8)
```

MapVec nightly:

```
test histogram::bench_histogram_with_label_values ... bench:         108 ns/iter (+/- 3)
```

cc #68

### CODE REVIEW

**Comment by siddontang** [comment]
Use 16/32/64 variable values to bench.

**Comment by BusyJay** [comment]
Why `MapVec` is faster? Did you try `BTreeMap`?

**Comment by overvenus** [comment]
BtreeMap is a little bit slower.

```
test histogram::bench_histogram_with_label_values ... bench:         111 ns/iter (+/- 2)
```

There is only one metric in this test, I will bench more.

**Comment by overvenus** [comment]
BtreeMap catchs MapVec when there are three metrics.

## Three metrics

### BtreeMap

```
test counter::bench_counter_with_prepared_mapped_labels ... bench:         189 ns/iter (+/- 4)
```

### MapVec

```
test counter::bench_counter_with_prepared_mapped_labels ... bench:         188 ns/iter (+/- 5)
```

## Six metrics

### BtreeMap

```
test counter::bench_counter_with_prepared_mapped_labels ... bench:         187 ns/iter (+/- 5)
```

### MapVec

```
test counter::bench_counter_with_prepared_mapped_labels ... bench:         188 ns/iter (+/- 27)
```

========

 Under typical usage, there will be three or more metrics in a MetricVec. I will switch to BtreeMap.

**Comment by siddontang** [comment]
How about more values?

**Comment by BusyJay** [comment]
How does `HashMap` perform in these situation?

**Comment by overvenus** [comment]
@BusyJay 

HashMap performs bad. Our key value is `<u64, Metric>`, `u64` is the hash code of a `Metric`'s label values(String), it is hashed by [fnv]. When we insert or get a `Metric`, HashMap hashes u64(it is unnecessary), that's why HashMap slow.

[fnv]: https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function

**Comment by BusyJay** [comment]
How about implement a custom `Hasher`?

**Comment by overvenus** [comment]
@BusyJay 

Still slow. Benchmark of cutsom fnv hasher can be found in https://github.com/pingcap/rust-prometheus/pull/70/commits/8471a9f389ccffdcef377913ca3fefeab8d0ee92.

I also write a hasher that does not hash `u64` at all, the benchmark is slower then fnv.

**Comment by overvenus** [comment]
## Benchmarks:

### HashMap

```
test counter::bench_counter_with_label_values_1  ... bench:          91 ns/iter (+/- 4)
test counter::bench_counter_with_label_values_16 ... bench:          91 ns/iter (+/- 7)
test counter::bench_counter_with_label_values_2  ... bench:          89 ns/iter (+/- 5)
test counter::bench_counter_with_label_values_32 ... bench:          90 ns/iter (+/- 18)
test counter::bench_counter_with_label_values_4  ... bench:          89 ns/iter (+/- 5)
test counter::bench_counter_with_label_values_64 ... bench:          89 ns/iter (+/- 9)
test counter::bench_counter_with_label_values_8  ... bench:          89 ns/iter (+/- 5)
```

### BTreeMap

```
test counter::bench_counter_with_label_values_1  ... bench:          85 ns/iter (+/- 4)
test counter::bench_counter_with_label_values_16 ... bench:          92 ns/iter (+/- 13)
test counter::bench_counter_with_label_values_2  ... bench:          82 ns/iter (+/- 1)
test counter::bench_counter_with_label_values_32 ... bench:          88 ns/iter (+/- 19)
test counter::bench_counter_with_label_values_4  ... bench:          83 ns/iter (+/- 12)
test counter::bench_counter_with_label_values_64 ... bench:          92 ns/iter (+/- 21)
test counter::bench_counter_with_label_values_8  ... bench:          87 ns/iter (+/- 10)
```

### MapVec

```
test counter::bench_counter_with_label_values_1  ... bench:          82 ns/iter (+/- 6)
test counter::bench_counter_with_label_values_16 ... bench:          82 ns/iter (+/- 12)
test counter::bench_counter_with_label_values_2  ... bench:          80 ns/iter (+/- 7)
test counter::bench_counter_with_label_values_32 ... bench:          86 ns/iter (+/- 4)
test counter::bench_counter_with_label_values_4  ... bench:          79 ns/iter (+/- 2)
test counter::bench_counter_with_label_values_64 ... bench:          93 ns/iter (+/- 6)
test counter::bench_counter_with_label_values_8  ... bench:          80 ns/iter (+/- 17)
```

[brenchmark file](https://gist.github.com/overvenus/7cbe3d81293a01f9c43f4c2691518eb5)

**Comment by siddontang** [comment]
why all uses less time this time?

**Comment by overvenus** [comment]
This time all benches only measure `with_label_values()`. 

I think we should use MapVec, it is pretty fast under typical usage(no more then 8). 

The real bottleneck is `RwLock::read()`, it costs about 50 ns per operation.

**Comment by overvenus** [comment]
## Benchmarks:

### lockfree-get-MapVec

Bench in single thread.

```
test counter::bench_counter_with_label_values_2         ... bench:          42 ns/iter (+/- 1)
test counter::bench_counter_with_label_values_4         ... bench:          42 ns/iter (+/- 1)
test counter::bench_counter_with_label_values_8         ... bench:          44 ns/iter (+/- 0)
```

The result is very promising, but there are still some problemes, e.g., potential data race, so it is not ready yet.

**Comment by siddontang** [comment]
where is the lock-free MapVec?

**Comment by overvenus** [comment]
Benchmark for https://github.com/pingcap/rust-prometheus/pull/70/commits/b69cc1c724c2faba80c8904634b259c35916f4e1

### Crossbeam MapVec

```
test counter::bench_counter_no_labels                   ... bench:           9 ns/iter (+/- 0)
test counter::bench_counter_with_label_values           ... bench:          46 ns/iter (+/- 1)
test counter::bench_counter_with_label_values_2         ... bench:          38 ns/iter (+/- 3)
test counter::bench_counter_with_label_values_4         ... bench:          39 ns/iter (+/- 1)
test counter::bench_counter_with_label_values_8         ... bench:          41 ns/iter (+/- 7)
```

**Comment by overvenus** [comment]
Based a long term effort, I realized a full featured resizable lock free map is not cheap.

It's `get` method needs at least two atomic instractions and a lock free memory reclamation (I chose [epoch-based memory reclamation (EBR)])

The map is structed as follows: 

```rust
struct LockFreeMap {
    // we need an indirection, because we want it to be resizable.
    root: AtomicPtr<Vec<(Key, AtomicPtr<Value>)>>, 
}

fn get(&self, k: Key) -> V {
    let map = self.root.atomic_load(); // one atomic instruction.
    let v = map.find(k).atomic_load(); // one or more atomic instructions.

    // Anything related with memory reclamation is omitted.
    // In fact, there will be more atomic instructions.

    v
}

// insert and resize are more complicated.
```

--------------------

CPU: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Memory: 16GB

The latest banchmark (based on EBR):

```
test counter::bench_counter_with_label_values_2         ... bench:          51 ns/iter (+/- 3)
test counter::bench_counter_with_label_values_4         ... bench:          53 ns/iter (+/- 6)
test counter::bench_counter_with_label_values_8         ... bench:          55 ns/iter (+/- 7)
```

The RWLock benchmark:

```
test counter::bench_counter_with_label_values_2         ... bench:          58 ns/iter (+/- 2)
test counter::bench_counter_with_label_values_4         ... bench:          59 ns/iter (+/- 5)
test counter::bench_counter_with_label_values_8         ... bench:          59 ns/iter (+/- 3)
```

[epoch-based memory reclamation (EBR)]: https://aturon.github.io/blog/2015/08/27/epoch/

**Pull request closed without merging**
