### PR TITLE
Cargo: support publish

### PR DESCRIPTION
**Pull request by siddontang**
@overvenus @BusyJay @disksing

### CODE REVIEW

**Comment by lucab** [comment]
Has anybody got in touch with @prepor to see if this could possibly take over the "prometheus" crate name from https://github.com/prepor/prometheus-rust?

**Comment by siddontang** [comment]
Hi @lucab 
We have not got in touch with @prepor now.
Of course, it is the best that we can use `prometheus` as the crate name :-)

**Comment by prepor** [comment]
Hello! I've added @siddontang as owner of prometheus crate.

**Comment by lucab** [comment]
Hi @prepor :smiley:
That's great, so may this one take over the existing crate? Are you planning on phasing out https://github.com/prepor/prometheus-rust? It is my understanding that the pingcap guys here are putting some efforts into having this library in a production-stable state and integrate it in other projects, which should ensure it is well-maintained in the long term.

**Comment by siddontang** [comment]
Thank you very much @prepor 
If you have any advice about this repo, please tell us. And it is very appreciated that you can develop with us too. 

I should learn how to publish our repo to the prometheus crate :-)

**Comment by siddontang** [comment]
PTAL @lucab @prepor

**Comment by prepor** [comment]
Good luck, guys ;)

**Comment by overvenus** [comment]
LGTM

**Comment by disksing** [comment]
LGTM

**Pull request merged**
