### PR TITLE
Add some documentation examples.

### PR DESCRIPTION
**Pull request by Hoverbear**
Add some additional documentation to the generated documentation.

### CODE REVIEW

**Comment by breeswish** [comment]
How about modifying the README as well? Or maybe providing a link to the README :)

**Comment by Hoverbear** [comment]
@breeswish There is a link right here https://github.com/pingcap/rust-prometheus/blob/master/README.md#prometheus-rust-client-library already

**Comment by siddontang** [comment]
Readme only contains a very simple example, I think it is fine to keep it.

But if you want to only provide in lib.rs, it is ok too.

**Comment by breeswish** [comment]
@siddontang Yeah, the point is to provide a link, told users that there are more documents in docs.rs and please check it out :P

**Comment by Hoverbear** [comment]
@breeswish I am not so worried about discover that way, when a user runs `cargo doc` on their own crate they will be able to see all the docs for this crate as well.

**Pull request merged**
