### PR TITLE
 Bump to version 0.3.4

### PR DESCRIPTION
**Pull request by overvenus**

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

But CI failed

**Comment by overvenus** [comment]
I think it is unrelated. It looks like the CI infrastructure is broken.

```
error: toolchain 'nightly' is not installed
info: caused by: not a directory: '/Users/travis/.rustup/toolchains/nightly-x86_64-apple-darwin'
```

**Comment by siddontang** [comment]
PTAL @BusyJay @disksing

**Comment by disksing** [comment]
LGTM

**Pull request merged**
