### PR TITLE
WIP: Counter Refine

### PR DESCRIPTION
**Pull request by breeswish**
WIP. Changes:

- [ ] WIP: Rearrange counter into multiple files to keep it clean.
- [x] Introduce `LocalCounterPrimitive`, which is some kind of a `LocalCounter` but not attached to any existing `Counter`. TiKV [self-implemented similar modules](https://github.com/pingcap/tikv/blob/master/src/coprocessor/local_metrics.rs#L36), which is a duplication. I think this library can provide such primitives so that we don't need to implement it again in TiKV.
- [x] Introduce `ICounter` trait (interface), to make `Counter`, `LocalCounter`, `LocalCounterPrimitive` compatible with each other (i.e. can be merged into another).
- [x] `inc_by` -> `try_inc_by` (#151)
- [ ] WIP: `LocalCounterVecPrimitive`.
- [ ] WIP: Eliminate locks in `LocalCouter` (question: do we really need `remove_label_values` in `LocalCounter`?)
- [ ] More to come.

Similar refinements will be applied to Histogram as well, later.

### CODE REVIEW

**Comment by breeswish** [comment]
@siddontang ideas or suggestions?

**Comment by siddontang** [comment]
IMO, I think ICounter is needless and introduces complexity. Why the Counter needs `merge` or `flush_to`?  Is it fine to let a Counter flush to a local counter? 

Btw, why do we need a CounterPrimitive? why not only providing a LocalCounter directly?

**Comment by breeswish** [comment]
@siddontang It's mainly for:
- CounterPrimitive flush to CounterPrimitive ([use case](https://github.com/AndreMouche/tikv/blob/de86b3d659097747def7dff61ca4b31dc97d6bba/src/coprocessor/local_metrics.rs#L42))
- CounterPrimitive flush to Counter ([use case](https://github.com/AndreMouche/tikv/blob/de86b3d659097747def7dff61ca4b31dc97d6bba/src/coprocessor/local_metrics.rs#L168))
- CounterPrimitive flush to LocalCounter ([use case](https://github.com/AndreMouche/tikv/blob/de86b3d659097747def7dff61ca4b31dc97d6bba/src/coprocessor/local_metrics.rs#L91))
- LocalCounter flush to Counter

So I make them `ICounter` in order to allowing flushing to each other.

**Comment by breeswish** [comment]
> Btw, why do we need a CounterPrimitive? why not only providing a LocalCounter directly?

Because `LocalCounter` is binded to a specific Counter, but sometimes we just need a simple counter (i.e. LocalCounterPrimitive) that can be flushed to somewhere else (maybe another LocalCounterPrimitive) and finally be flushed into a real Counter (i.e. LocalCounter). For example, this [`ScanCounter`](https://github.com/pingcap/tikv/blob/master/src/coprocessor/local_metrics.rs#L36) is a self-implementing a `LocalCounterPrimitive`. Once we have a `LocalCounterPrimitive`, these code can be simplified.

Also, please consider some more complex use cases, for example, it is not a counter, but a CounterVec, or a HistogramVec. Self-implementing such modules is some kind of duplication. If we could just provide very primitive structures for handling these tasks, it will be nicer.

**Comment by siddontang** [comment]
This is a Prometheus library, please notice it. So why we need to provide a primitive type for other use? 
Don't over design.

**Comment by breeswish** [comment]
@siddontang Simply speaking, is to provide a metrics collecting facility which is not binded to a specific metrics *at the time of constructing*. This brings better flexibility. 

For example, for a single function, by using this primitive type, it can "tell others what kind of metrics I have" and the caller is free to collect some of them into a specific global metric, instead of letting the caller to inform the function (or hard coded a target metrics in the function) "what metrics you need to collect to".

This pattern is widely used in TiKV. e.g. in coprocessor executors, the executor itself is responsible for collecting seek counts, point lookup counts, etc. However the executor does not know where these counts should be collected into (because of lacking some other knowledge). The caller deep outside is responsible for aggregating all useful informations (labels) and its metrics into a global or local metrics.

**Comment by breeswish** [comment]
Split into several PRs later. Closing.

**Pull request closed without merging**
