### PR TITLE
Rust 2018

### PR DESCRIPTION
**Pull request by brson**
This upgrades prometheus to 2018 and bumps the version from 0.5 to 0.6.

Unfortunately I haven't been able to test this against tikv/master: tikv is currently on prometheus 0.4, and 0.5 added a dependency on openssl that doesn't link with tikv for mysterious reasons that I haven't investigated. Still, i don't have much expectation that just upgrading to 2018 will cause incomptabilities with tikv's current toolchain.

This will conflict a lot with https://github.com/pingcap/rust-prometheus/pull/216, so it might be appropriate to get that landed and let me deal with rebasing.

Fixes https://github.com/pingcap/rust-prometheus/issues/217

PTAL @overvenus

### CODE REVIEW

**Comment by brson** [comment]
There's been a complication with the tikv toolchain upgrade (https://github.com/tikv/tikv/pull/4138#issuecomment-458649545), so we might want to wait on this to see how that turns out.

**Comment by brson** [comment]
Tikv is upgraded to 2018 now. Waiting on https://github.com/pingcap/rust-prometheus/pull/216 to land then I'll rebase.

**Comment by brson** [comment]
#216 is landed. I'll rebase this tomorrow.

**Comment by brson** [comment]
I've rebased this PR.

Now it builds on an unrelated fix in https://github.com/pingcap/rust-prometheus/pull/225, so please merge that first (or just merge this and close that - it doesn't particularly matter).

PTAL @overvenus / @breeswish

**Comment by brson** [comment]
I added a version bump in case this breaks toolchain compatibility, though I haven't tested on anything before 1.32.

**Comment by overvenus** [comment]
There are some warnings on CI, looks like they needs `crate::`.

<details>
  <summary>unresolved import `...`</summary>
<pre>
error[E0432]: unresolved import `encoder`
  --> src/push.rs:23:5
   |
23 | use encoder::{Encoder, ProtobufEncoder};
   |     ^^^^^^^ did you mean `crate::encoder`?
   |
   = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>
error[E0432]: unresolved import `errors`
  --> src/push.rs:24:5
   |
24 | use errors::{Error, Result};
   |     ^^^^^^ did you mean `crate::errors`?
   |
   = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>
error[E0432]: unresolved import `metrics`
  --> src/push.rs:25:5
   |
25 | use metrics::Collector;
   |     ^^^^^^^ did you mean `crate::metrics`?
   |
   = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>
error[E0432]: unresolved import `proto`
  --> src/push.rs:26:5
   |
26 | use proto;
   |     ^^^^^ no `proto` external crate
error[E0432]: unresolved import `registry`
  --> src/push.rs:27:5
   |
27 | use registry::Registry;
   |     ^^^^^^^^ did you mean `crate::registry`?
   |
   = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>
error[E0432]: unresolved import `encoder`
  --> src/push.rs:23:5
   |
23 | use encoder::{Encoder, ProtobufEncoder};
   |     ^^^^^^^ did you mean `crate::encoder`?
   |
   = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>
error[E0432]: unresolved import `errors`
  --> src/push.rs:24:5
   |
24 | use errors::{Error, Result};
   |     ^^^^^^ did you mean `crate::errors`?
   |
   = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>
error[E0432]: unresolved import `metrics`
  --> src/push.rs:25:5
   |
25 | use metrics::Collector;
   |     ^^^^^^^ did you mean `crate::metrics`?
   |
   = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>
error[E0432]: unresolved import `proto`
  --> src/push.rs:26:5
   |
26 | use proto;
   |     ^^^^^ no `proto` external crate
error[E0432]: unresolved import `registry`
  --> src/push.rs:27:5
   |
27 | use registry::Registry;
   |     ^^^^^^^^ did you mean `crate::registry`?
   |
   = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>
error: unused import: `Encoder`
  --> src/push.rs:23:15
   |
23 | use encoder::{Encoder, ProtobufEncoder};
   |               ^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`
error: unused import: `Encoder`
  --> src/push.rs:23:15
   |
23 | use encoder::{Encoder, ProtobufEncoder};
   |               ^^^^^^^
   |
   = note: `-D unused-imports` implied by `-D warnings`
error: unused import: `proto`
   --> src/push.rs:268:9
    |
268 |     use proto;
    |         ^^^^^
</pre>
</details>

**Comment by brson** [comment]
Rebased and fixed for non-default features. Waiting to see what CI says.

**Comment by brson** [comment]
This is passing now. Please have another look @overvenus

**Comment by brson** [comment]
Looks like this is superseded by https://github.com/pingcap/rust-prometheus/pull/226

**Pull request closed without merging**
