### PR TITLE
histogram: expose LocalHistogram

### PR DESCRIPTION
**Pull request by BusyJay**
Currently there is no way to declare a variable has type `LocalHistogram`.

@siddontang @overvenus PTAL

### CODE REVIEW

**Comment by siddontang** [comment]
CI failed

**Comment by BusyJay** [comment]
CI failure doesn't seem to be related to these changes.

**Comment by siddontang** [comment]
@overvenus Please fix the CI later. I will merge this PR now because TiKV needs it.

**Comment by overvenus** [comment]
Okay, I will give it a try.

**Pull request merged**
