### PR TITLE
Provide try_inc_by to counters to avoid panics

### PR DESCRIPTION
**Pull request by breeswish**
Users can choice to avoid panics by calling `try_inc_by()`.

### CODE REVIEW

**Comment by siddontang** [comment]
Do you think anyone will use this API to replace `inc_by`? 

I think this solves nothing.

**Comment by BusyJay** [comment]
Since int counter is not part of spec, then handling overflow feels like an undefined behavior to me. Then it looks OK and convenient to let it overflow when compiling without `debug-assertions`, which is also the default strategy of rust builtin int types.

**Comment by siddontang** [comment]
@breeswish 

I prefer removing try and ignoring the overflow or handling it in debug. Letting the user handle `try` explicitly help nothing but increases the load.

**Comment by BusyJay** [comment]
Any updates?

**Pull request closed without merging**
